/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2025.03                                                     */
/* Component Version:  V2024.09                                                     */
/* CAS Version:        V.04.00M0P03062025                                           */
/* SAS Version:        V.04.00M0P030625                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       0359bb79-b2bb-4824-8472-b0e048b7bfa4                         */
/* Node GUID:          42dd2510-f6c4-4e17-927c-fbf69847579f                         */
/* Node Id:            3YI7UJX0PHQEVS9V6ZEEPE2ZJ                                    */
/* Algorithm:          Decision Tree                                                */
/* Generated by:       geldmui@gelenable.sas.com                                    */
/* Date:               02OCT2025:22:56:39                                           */
/*----------------------------------------------------------------------------------*/
*------------------------------------------------------------*;
*Nodeid: _82MWN0LJ5UAN11VR4B3E4LZ9X;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
*Nodeid: _3YI7UJX0PHQEVS9V6ZEEPE2ZJ;
*------------------------------------------------------------*;
/*---------------------------------------------------------
   SAS Code Generated by Cloud Analytic Services for Decision Tree
     Date                  : 02Oct2025:22:54:02 UTC
     Number of Nodes       : 53
     Number of Tree Depth  : 6
     Number of Bins        : 50
     Number of Obs         : 5960
     -------------------------------------------------------*/

   length _strfmt_3390_ $7; drop _strfmt_3390_;
   _strfmt_3390_ = ' ';

   length P_BAD 8;
   P_BAD = .;
   label P_BAD = 'Predicted: BAD';

   _node_id_ =  0;
   _new_id_  = -1;
   nextnode_3390:
   if _node_id_ eq 0 then do;
         _numval_ = DELINQ;
         if missing(_numval_) then do;
            _node_id_ = 1;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 1) then do;

            _new_id_ = 1;
         end;
         else if (_numval_ ge 1 and _numval_ lt 15) then do;

            _new_id_ = 2;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 1;
         end;
         else if (_numval_ ge 15) then do;
            _new_id_ = 2;
         end;
         else do;
         _new_id_ = 1;
         end;
   end;
   else if _node_id_ eq 1 then do;
         _numval_ = DEBTINC;
         if missing(_numval_) then do;
            _node_id_ = 4;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0.52449921542988 and _numval_ lt 44.4813068896627) then do;

            _new_id_ = 3;
         end;
         else if (_numval_ ge 44.4813068896627 and _numval_ lt 203.312148691165) then do;

            _new_id_ = 4;
         end;
         else if (_numval_ lt 0.52449921542988) then do;
            _new_id_ = 3;
         end;
         else if (_numval_ ge 203.312148691165) then do;
            _new_id_ = 4;
         end;
         else do;
         _new_id_ = 3;
         end;
   end;
   else if _node_id_ eq 2 then do;
         _numval_ = VALUE;
         if missing(_numval_) then do;
            _node_id_ = 5;
            goto nextnode_3390;
         end;
         if (_numval_ ge 8000 and _numval_ lt 36808.64) then do;

            _new_id_ = 5;
         end;
         else if (_numval_ ge 36808.64 and _numval_ lt 855909) then do;

            _new_id_ = 6;
         end;
         else if (_numval_ lt 8000) then do;
            _new_id_ = 5;
         end;
         else if (_numval_ ge 855909) then do;
            _new_id_ = 6;
         end;
         else do;
         _new_id_ = 6;
         end;
   end;
   else if _node_id_ eq 3 then do;
         _numval_ = VALUE;
         if missing(_numval_) then do;
            _node_id_ = 8;
            goto nextnode_3390;
         end;
         if (_numval_ ge 8000 and _numval_ lt 855909) then do;

            _new_id_ = 7;
         end;
         else if (_numval_ lt 8000) then do;
            _new_id_ = 7;
         end;
         else if (_numval_ ge 855909) then do;
            _new_id_ = 7;
         end;
         else do;
         _new_id_ = 7;
         end;
   end;
   else if _node_id_ eq 4 then do;
         _numval_ = CLAGE;
         if missing(_numval_) then do;
            _node_id_ = 9;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 173.466666666667) then do;

            _new_id_ = 9;
         end;
         else if (_numval_ ge 173.466666666667 and _numval_ lt 1168.23356094464) then do;

            _new_id_ = 10;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 9;
         end;
         else if (_numval_ ge 1168.23356094464) then do;
            _new_id_ = 10;
         end;
         else do;
         _new_id_ = 9;
         end;
   end;
   else if _node_id_ eq 5 then do;
         _numval_ = VALUE;
         if missing(_numval_) then do;
            _node_id_ = 11;
            goto nextnode_3390;
         end;
         if (_numval_ ge 8000 and _numval_ lt 30802.72) then do;

            _new_id_ = 11;
         end;
         else if (_numval_ ge 30802.72 and _numval_ lt 855909) then do;

            _new_id_ = 12;
         end;
         else if (_numval_ lt 8000) then do;
            _new_id_ = 11;
         end;
         else if (_numval_ ge 855909) then do;
            _new_id_ = 12;
         end;
         else do;
         _new_id_ = 11;
         end;
   end;
   else if _node_id_ eq 6 then do;
         _numval_ = DEROG;
         if missing(_numval_) then do;
            _node_id_ = 13;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 1) then do;

            _new_id_ = 13;
         end;
         else if (_numval_ ge 1 and _numval_ lt 10) then do;

            _new_id_ = 14;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 13;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 14;
         end;
         else do;
         _new_id_ = 13;
         end;
   end;
   else if _node_id_ eq 7 then do;
         _numval_ = CLAGE;
         if missing(_numval_) then do;
            _node_id_ = 15;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 173.466666666667) then do;

            _new_id_ = 15;
         end;
         else if (_numval_ ge 173.466666666667 and _numval_ lt 1168.23356094464) then do;

            _new_id_ = 16;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 15;
         end;
         else if (_numval_ ge 1168.23356094464) then do;
            _new_id_ = 16;
         end;
         else do;
         _new_id_ = 15;
         end;
   end;
   else if _node_id_ eq 8 then do;
         _numval_ = YOJ;
         if missing(_numval_) then do;
            _node_id_ = 18;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 41) then do;

            _new_id_ = 17;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 17;
         end;
         else if (_numval_ ge 41) then do;
            _new_id_ = 17;
         end;
         else do;
         _new_id_ = 17;
         end;
   end;
   else if _node_id_ eq 9 then do;
         _numval_ = DEBTINC;
         if missing(_numval_) then do;
            _node_id_ = 20;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0.52449921542988 and _numval_ lt 203.312148691165) then do;

            _new_id_ = 19;
         end;
         else if (_numval_ lt 0.52449921542988) then do;
            _new_id_ = 19;
         end;
         else if (_numval_ ge 203.312148691165) then do;
            _new_id_ = 19;
         end;
         else do;
         _new_id_ = 20;
         end;
   end;
   else if _node_id_ eq 10 then do;
         _numval_ = DEROG;
         if missing(_numval_) then do;
            _node_id_ = 21;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 1) then do;

            _new_id_ = 21;
         end;
         else if (_numval_ ge 1 and _numval_ lt 10) then do;

            _new_id_ = 22;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 21;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 22;
         end;
         else do;
         _new_id_ = 21;
         end;
   end;
   else if _node_id_ eq 11 then do;
         _strfmt_3390_ = left(trim(put(JOB,$7.)));
         if _strfmt_3390_ in ('Self',
         'Other',
         'ProfExe',
         '',
         'Mgr') then do;

         _new_id_ = 23;
         end;
         else if _strfmt_3390_ in ('Office') then do;

         _new_id_ = 24;
         end;
         else if MISSING(JOB) then do;
         _new_id_ = 23;
         end;
         else do;
         _new_id_ = 23;
         end;
   end;
   else if _node_id_ eq 12 then do;
         _numval_ = MORTDUE;
         if missing(_numval_) then do;
            _node_id_ = 26;
            goto nextnode_3390;
         end;
         if (_numval_ ge 2063 and _numval_ lt 65017) then do;

            _new_id_ = 25;
         end;
         else if (_numval_ ge 65017 and _numval_ lt 399550) then do;

            _new_id_ = 26;
         end;
         else if (_numval_ lt 2063) then do;
            _new_id_ = 25;
         end;
         else if (_numval_ ge 399550) then do;
            _new_id_ = 26;
         end;
         else do;
         _new_id_ = 25;
         end;
   end;
   else if _node_id_ eq 13 then do;
         _numval_ = DELINQ;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 0 and _numval_ lt 3) then do;

            _new_id_ = 27;
         end;
         else if (_numval_ ge 3 and _numval_ lt 15) then do;

            _new_id_ = 28;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 27;
         end;
         else if (_numval_ ge 15) then do;
            _new_id_ = 28;
         end;
         else do;
         _new_id_ = 27;
         end;
   end;
   else if _node_id_ eq 14 then do;
         _numval_ = VALUE;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 8000 and _numval_ lt 121857.919999999) then do;

            _new_id_ = 29;
         end;
         else if (_numval_ ge 121857.919999999 and _numval_ lt 855909) then do;

            _new_id_ = 30;
         end;
         else if (_numval_ lt 8000) then do;
            _new_id_ = 29;
         end;
         else if (_numval_ ge 855909) then do;
            _new_id_ = 30;
         end;
         else do;
         _new_id_ = 29;
         end;
   end;
   else if _node_id_ eq 15 then do;
         _numval_ = LOAN;
         if missing(_numval_) then do;
            _node_id_ = 32;
            goto nextnode_3390;
         end;
         if (_numval_ ge 1100 and _numval_ lt 4500) then do;

            _new_id_ = 31;
         end;
         else if (_numval_ ge 4500 and _numval_ lt 89900) then do;

            _new_id_ = 32;
         end;
         else if (_numval_ lt 1100) then do;
            _new_id_ = 31;
         end;
         else if (_numval_ ge 89900) then do;
            _new_id_ = 32;
         end;
         else do;
         _new_id_ = 32;
         end;
   end;
   else if _node_id_ eq 16 then do;
         _numval_ = VALUE;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 8000 and _numval_ lt 258730.88) then do;

            _new_id_ = 33;
         end;
         else if (_numval_ ge 258730.88 and _numval_ lt 855909) then do;

            _new_id_ = 34;
         end;
         else if (_numval_ lt 8000) then do;
            _new_id_ = 33;
         end;
         else if (_numval_ ge 855909) then do;
            _new_id_ = 34;
         end;
         else do;
         _new_id_ = 33;
         end;
   end;
   else if _node_id_ eq 17 then do;
         _leaf_id_ = 17;
         _new_id_ = -1;
         P_BAD =                    1;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 18 then do;
         _leaf_id_ = 18;
         _new_id_ = -1;
         P_BAD =                    0;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 19 then do;
         _numval_ = NINQ;
         if missing(_numval_) then do;
            _node_id_ = 35;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 7) then do;

            _new_id_ = 35;
         end;
         else if (_numval_ ge 7 and _numval_ lt 17) then do;

            _new_id_ = 36;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 35;
         end;
         else if (_numval_ ge 17) then do;
            _new_id_ = 36;
         end;
         else do;
         _new_id_ = 35;
         end;
   end;
   else if _node_id_ eq 20 then do;
         _strfmt_3390_ = left(trim(put(JOB,$7.)));
         if _strfmt_3390_ in ('Self',
         'Other',
         'Sales',
         'Mgr') then do;

         _new_id_ = 37;
         end;
         else if _strfmt_3390_ in ('Office',
         'ProfExe',
         '') then do;

         _new_id_ = 38;
         end;
         else if MISSING(JOB) then do;
         _new_id_ = 38;
         end;
         else do;
         _new_id_ = 37;
         end;
   end;
   else if _node_id_ eq 21 then do;
         _strfmt_3390_ = left(trim(put(JOB,$7.)));
         if _strfmt_3390_ in ('Other',
         'ProfExe',
         'Sales',
         'Mgr') then do;

         _new_id_ = 39;
         end;
         else if _strfmt_3390_ in ('Self',
         'Office',
         '') then do;

         _new_id_ = 40;
         end;
         else if MISSING(JOB) then do;
         _new_id_ = 40;
         end;
         else do;
         _new_id_ = 39;
         end;
   end;
   else if _node_id_ eq 22 then do;
         _numval_ = VALUE;
         if missing(_numval_) then do;
            _node_id_ = 41;
            goto nextnode_3390;
         end;
         if (_numval_ ge 8000 and _numval_ lt 41234.28) then do;

            _new_id_ = 41;
         end;
         else if (_numval_ ge 41234.28 and _numval_ lt 855909) then do;

            _new_id_ = 42;
         end;
         else if (_numval_ lt 8000) then do;
            _new_id_ = 41;
         end;
         else if (_numval_ ge 855909) then do;
            _new_id_ = 42;
         end;
         else do;
         _new_id_ = 42;
         end;
   end;
   else if _node_id_ eq 23 then do;
         _leaf_id_ = 23;
         _new_id_ = -1;
         P_BAD =                    1;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 24 then do;
         _numval_ = CLNO;
         if missing(_numval_) then do;
            _node_id_ = 43;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 20) then do;

            _new_id_ = 43;
         end;
         else if (_numval_ ge 20 and _numval_ lt 71) then do;

            _new_id_ = 44;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 43;
         end;
         else if (_numval_ ge 71) then do;
            _new_id_ = 44;
         end;
         else do;
         _new_id_ = 43;
         end;
   end;
   else if _node_id_ eq 25 then do;
         _strfmt_3390_ = left(trim(put(JOB,$7.)));
         if _strfmt_3390_ in ('Other',
         'Sales') then do;

         _new_id_ = 45;
         end;
         else if _strfmt_3390_ in ('Office') then do;

         _new_id_ = 46;
         end;
         else if MISSING(JOB) then do;
         _new_id_ = 45;
         end;
         else do;
         _new_id_ = 45;
         end;
   end;
   else if _node_id_ eq 26 then do;
         _leaf_id_ = 26;
         _new_id_ = -1;
         P_BAD =     0.33333333333333;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 27 then do;
         _numval_ = NINQ;
         if missing(_numval_) then do;
            _node_id_ = 48;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 1) then do;

            _new_id_ = 47;
         end;
         else if (_numval_ ge 1 and _numval_ lt 17) then do;

            _new_id_ = 48;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 47;
         end;
         else if (_numval_ ge 17) then do;
            _new_id_ = 48;
         end;
         else do;
         _new_id_ = 48;
         end;
   end;
   else if _node_id_ eq 28 then do;
         _numval_ = DEROG;
         if missing(_numval_) then do;
            _node_id_ = 50;
            goto nextnode_3390;
         end;
         if (_numval_ ge 0 and _numval_ lt 10) then do;

            _new_id_ = 49;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 49;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 49;
         end;
         else do;
         _new_id_ = 49;
         end;
   end;
   else if _node_id_ eq 29 then do;
         _numval_ = DEROG;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 0 and _numval_ lt 3) then do;

            _new_id_ = 51;
         end;
         else if (_numval_ ge 3 and _numval_ lt 10) then do;

            _new_id_ = 52;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 51;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 52;
         end;
         else do;
         _new_id_ = 51;
         end;
   end;
   else if _node_id_ eq 30 then do;
         _leaf_id_ = 30;
         _new_id_ = -1;
         P_BAD =                    1;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 31 then do;
         _leaf_id_ = 31;
         _new_id_ = -1;
         P_BAD =                  0.4;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 32 then do;
         _leaf_id_ = 32;
         _new_id_ = -1;
         P_BAD =     0.06937307297019;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 33 then do;
         _leaf_id_ = 33;
         _new_id_ = -1;
         P_BAD =     0.01889848812095;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 34 then do;
         _leaf_id_ = 34;
         _new_id_ = -1;
         P_BAD =     0.13333333333333;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 35 then do;
         _leaf_id_ = 35;
         _new_id_ = -1;
         P_BAD =                    1;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 36 then do;
         _leaf_id_ = 36;
         _new_id_ = -1;
         P_BAD =                  0.8;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 37 then do;
         _leaf_id_ = 37;
         _new_id_ = -1;
         P_BAD =     0.68882175226586;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 38 then do;
         _leaf_id_ = 38;
         _new_id_ = -1;
         P_BAD =     0.49112426035502;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 39 then do;
         _leaf_id_ = 39;
         _new_id_ = -1;
         P_BAD =     0.31696428571428;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 40 then do;
         _leaf_id_ = 40;
         _new_id_ = -1;
         P_BAD =     0.09615384615384;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 41 then do;
         _leaf_id_ = 41;
         _new_id_ = -1;
         P_BAD =                    1;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 42 then do;
         _leaf_id_ = 42;
         _new_id_ = -1;
         P_BAD =     0.56756756756756;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 43 then do;
         _leaf_id_ = 43;
         _new_id_ = -1;
         P_BAD =                  0.6;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 44 then do;
         _leaf_id_ = 44;
         _new_id_ = -1;
         P_BAD =                    1;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 45 then do;
         _leaf_id_ = 45;
         _new_id_ = -1;
         P_BAD =                    1;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 46 then do;
         _leaf_id_ = 46;
         _new_id_ = -1;
         P_BAD =                  0.6;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 47 then do;
         _leaf_id_ = 47;
         _new_id_ = -1;
         P_BAD =     0.16207951070336;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 48 then do;
         _leaf_id_ = 48;
         _new_id_ = -1;
         P_BAD =     0.36060606060606;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 49 then do;
         _leaf_id_ = 49;
         _new_id_ = -1;
         P_BAD =     0.64661654135338;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 50 then do;
         _leaf_id_ = 50;
         _new_id_ = -1;
         P_BAD =     0.24489795918367;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 51 then do;
         _leaf_id_ = 51;
         _new_id_ = -1;
         P_BAD =                  0.5;
         label P_BAD = 'Predicted: BAD';
   end;
   else if _node_id_ eq 52 then do;
         _leaf_id_ = 52;
         _new_id_ = -1;
         P_BAD =     0.91891891891891;
         label P_BAD = 'Predicted: BAD';
   end;
   if _new_id_ >= 0 then do;
       _node_id_ = _new_id_;
      goto nextnode_3390;
   end;

   drop _numval_;
   drop _node_id_;
   drop _new_id_;




   *------------------------------------------------------------*;
   * Accounting for missing predicted variable;
   *------------------------------------------------------------*;
   label "P_BAD"n ='Predicted: BAD';
   if "P_BAD"n = . then "P_BAD"n =0.1994966443;
*------------------------------------------------------------*;
* Generating fixed output names;
*------------------------------------------------------------*;
Length EM_PREDICTION 8;
LABEL EM_PREDICTION= "Prediction for BAD";
EM_PREDICTION= 'P_BAD'n;
