/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2025.03                                                     */
/* Component Version:  V2024.09                                                     */
/* CAS Version:        V.04.00M0P03062025                                           */
/* SAS Version:        V.04.00M0P030625                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       4d1336f3-908c-4dac-b31c-1c606f1a3e98                         */
/* Node GUID:          9e20a049-09f1-4db1-a603-9d780a5c809a                         */
/* Node Id:            9D0JFD0L7TWDD4NQBT3SBFQU2                                    */
/* Algorithm:          Gradient Boosting                                            */
/* Generated by:       geldmui@gelenable.sas.com                                    */
/* Date:               30SEP2025:21:49:33                                           */
/*----------------------------------------------------------------------------------*/
data sasep.out;
   dcl package score _9D0JFD0L7TWDD4NQBT3SBFQU2();
   dcl double EM_PREDICTION;
   dcl varchar(7) "JOB" having label n'JOB';
   dcl varchar(7) "REASON" having label n'REASON';
   dcl double "CLAGE" having label n'CLAGE';
   dcl double "CLNO" having label n'CLNO';
   dcl double "DEBTINC" having label n'DEBTINC';
   dcl double "DELINQ" having label n'DELINQ';
   dcl double "DEROG" having label n'DEROG';
   dcl double "LOAN" having label n'LOAN';
   dcl double "MORTDUE" having label n'MORTDUE';
   dcl double "NINQ" having label n'NINQ';
   dcl double "VALUE" having label n'VALUE';
   dcl double "YOJ" having label n'YOJ';
   dcl double "P_BAD" having label n'Predicted: BAD';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   varlist allvars [_all_];
 
    
   method init();
      _9D0JFD0L7TWDD4NQBT3SBFQU2.setvars(allvars);
      _9D0JFD0L7TWDD4NQBT3SBFQU2.setkey(n'732BC7F2F26FBE3231623CD94A35340DE17A0A3F');
   end;
    
   method post_9D0JFD0L7TWDD4NQBT3SBFQU2();
      dcl double _P_;
       
      if "P_BAD" = . then "P_BAD" = 0.1994966443;
      EM_PREDICTION = "P_BAD";
    
   end;
    
 
   method run();
      set SASEP.IN;
      _9D0JFD0L7TWDD4NQBT3SBFQU2.scoreRecord();
      post_9D0JFD0L7TWDD4NQBT3SBFQU2();
   end;
 
   method term();
   end;
 
enddata;
